apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}"
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: web
      nodePort: {{ .Values.webapp.nodePort }}
  selector:
    name: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}"
  template:
    metadata:
      labels:
        name: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}"
    spec:
      restartPolicy: "Always"
      containers:
        - name: whatsapp-web
          image: "{{ .Values.webapp.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: "0.15"
              memory: 128Mi
          ports:
            - containerPort: 443
              protocol: TCP
              name: web
          env:
            - name: WACORE_HOSTNAME
              value: "{{ .Values.clientId }}-{{ .Values.coreapp.hostnamePostfix }}"
            - name: WA_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: whatsapp-config
                  key: wa-db-engine
            - name: WA_APP_MULTICONNECT
              value: '0'
            - name: WA_DB_NAME_PREFIX
              value: "{{ .Values.clientId }}_"
            - name: WA_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: whatsapp-config
                  key: wa-db-hostname
            - name: WA_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: whatsapp-config
                  key: wa-db-port
            - name: WA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: whatsapp-config
                  key: wa-db-username
            - name: WA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whatsapp-config
                  key: wa-db-password
            - name: WA_WEB_SERVERNAME
              value: "{{ .Values.clientId }}-{{ .Values.webapp.hostnamePostfix }}"
          volumeMounts:
            - name: whatsapp-media
              mountPath: "/usr/local/media_storage"
      volumes:
        - name: whatsapp-media
          persistentVolumeClaim:
            claimName: media-volume-claim
