apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.client.id }}-{{ .Values.coreapp.hostnamePostfix }}"
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterIP: None
  ports:
    - port: 6250
      targetPort: 6250
      protocol: TCP
      name: messaging
    - port: 6251
      targetPort: 6251
      protocol: TCP
      name: contacts
    - port: 6252
      targetPort: 6252
      protocol: TCP
      name: control
    - port: 6253
      targetPort: 6253
      protocol: TCP
      name: healthcheck
  selector:
    name: "{{ .Values.client.id }}-{{ .Values.coreapp.hostnamePostfix }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.client.id }}-{{ .Values.coreapp.hostnamePostfix }}-deployment"
  namespace: {{ .Values.cluster.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{ .Values.client.id }}-{{ .Values.coreapp.hostnamePostfix }}"
  template:
    metadata:
      labels:
        name: "{{ .Values.client.id }}-{{ .Values.coreapp.hostnamePostfix }}"
    spec:
      restartPolicy: "Always"
      containers:
        - name: whatsapp-coreapp
          image: "{{ .Values.coreapp.repository }}:{{ .Values.coreapp.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: "0.15"
              memory: 128Mi
          ports:
            - containerPort: 6250
              protocol: TCP
              name: messaging
            - containerPort: 6251
              protocol: TCP
              name: contacts
            - containerPort: 6252
              protocol: TCP
              name: control
            - containerPort: 6253
              protocol: TCP
              name: healthcheck
          env:
            - name: WA_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-engine
            - name: WA_DB_NAME_PREFIX
              value: "{{ .Values.client.id }}_"
            - name: WA_TCP_LISTEN_ADDRESS
              value: 'any'
            - name: WA_APP_MULTICONNECT
              value: '0'
            - name: WA_CONFIG_ON_DB
              value: '1'
            - name: COREAPP_EXTERNAL_PORTS
              value: '6250,6251,6252,6253'
            - name: WA_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-hostname
            - name: WA_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-port
            - name: WA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-username
            - name: WA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-password
            - name: WA_DB_CONNECTION_IDLE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config }}
                  key: wa-db-connection-idle-timeout
            - name: COREAPP_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: whatsapp-media
              mountPath: "/usr/local/media_storage"
              subPath: {{ .Values.client.id }}
      volumes:
        - name: whatsapp-media
          nfs:
            server: nfs-service
            path: /
