apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - name: "33060"
    port: 33060
    targetPort: 3306
  - name: 33060-tcp
    port: 33060
    targetPort: 33060
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
