apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: waweb
  name: waweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: waweb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: waweb
    spec:
      containers:
      - args:
        - /opt/whatsapp/bin/wait_on_postgres.sh
        - /opt/whatsapp/bin/launch_within_docker.sh
        env:
        - name: ORCHESTRATION
          value: DOCKER-COMPOSE
        - name: WACORE_HOSTNAME
          value: wacore
        - name: WA_DB_ENGINE
          valueFrom:
            configMapKeyRef:
              key: WA_DB_ENGINE
              name: db-env
        - name: WA_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: WA_DB_HOSTNAME
              name: db-env
        - name: WA_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: WA_DB_PASSWORD
              name: db-env
        - name: WA_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: WA_DB_PORT
              name: db-env
        - name: WA_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: WA_DB_USERNAME
              name: db-env
        - name: WA_RUNNING_ENV_VERSION
          value: v2.2.3
        image: docker.whatsapp.biz/web:v2.35.2
        imagePullPolicy: ""
        name: waweb
        ports:
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/wamedia
          name: whatsappMedia
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: whatsappMedia
        persistentVolumeClaim:
          claimName: whatsappMedia
status: {}
