apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: waweb
  name: waweb
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 443
  selector:
    io.kompose.service: waweb
status:
  loadBalancer: {}
